language: rust

matrix:
  include:
    - rust: 1.22.1
    - rust: beta
    - rust: nightly
  allow_failures:
    - rust: nightly

script:
  - cargo build --verbose
  - |
      if [ "$TRAVIS_RUST_VERSION" = nightly ]; then
          cargo install clippy --debug
          cargo clippy -- -Dclippy
      fi
  - cargo test --verbose
