[package]
name = "saphyr-bench"
authors = [ "Ethiraric <ethiraric@gmail.com>" ]
description = "Utilities to benchmark saphyr"
license = "MIT"
readme = "README.md"
edition = { workspace = true }
version = { workspace = true }

[dependencies]
saphyr-parser = { workspace = true }
